import json

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source, outputs=None):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": outputs or [],
        "source": source
    }

cells = []

# ── SECTION 0: TITLE ──────────────────────────────────────────
cells.append(md([
    "# ARX Model – Greenhouse Soil Moisture Prediction\n",
    "## Notebook thực hành đầy đủ\n",
    "\n",
    "**ARX(2, 2, 1)** | MISO | Least Squares | Preprocessing | Model Evaluation\n",
    "\n",
    "---\n",
    "### Cấu trúc Notebook\n",
    "| # | Phần | Mô tả |\n",
    "|---|------|-------|\n",
    "| 1 | Setup | Cài đặt thư viện |\n",
    "| 2 | Lý thuyết | Mô hình ARX, phương trình |\n",
    "| 3 | Dữ liệu | Tạo / tải + **Preprocessing** (lọc nhiễu, chuẩn hóa) |\n",
    "| 4 | Regression Matrix | Xây dựng ma trận X, Y |\n",
    "| 5 | Ước lượng tham số | Least Squares |\n",
    "| 6 | Dự đoán | One-step & Simulation |\n",
    "| 7 | Đánh giá | RMSE, FIT, R², AIC, BIC |\n",
    "| 8 | Residuals | Phân tích phần dư |\n",
    "| 9 | Model Selection | So sánh các bậc mô hình |\n",
    "| 10 | Kết luận | Tổng kết & hướng mở rộng |",
]))

# ── SECTION 1: SETUP ──────────────────────────────────────────
cells.append(md(["# 1. Setup & Import Thư Viện\n",
    "Cài đặt các thư viện cần thiết. Nếu chưa cài, chạy cell bên dưới."]))

cells.append(code([
    "# Cài đặt (bỏ comment nếu cần)\n",
    "# !pip install numpy pandas matplotlib scipy scikit-learn statsmodels"
]))

cells.append(code([
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec\n",
    "from scipy import stats\n",
    "from sklearn.metrics import r2_score\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Matplotlib settings\n",
    "plt.rcParams.update({\n",
    "    'figure.figsize': (14, 5),\n",
    "    'axes.grid': True,\n",
    "    'grid.alpha': 0.3,\n",
    "    'font.size': 11,\n",
    "})\n",
    "\n",
    "print('✅ Libraries imported successfully')\n",
    "print(f'NumPy:  {np.__version__}')\n",
    "print(f'Pandas: {pd.__version__}')\n"
]))

# ── SECTION 2: THEORY ─────────────────────────────────────────
cells.append(md([
    "# 2. Lý Thuyết ARX Model\n",
    "\n",
    "## 2.1 Định nghĩa\n",
    "Mô hình **ARX(na, nb, nk)** có dạng tổng quát:\n",
    "$$A(q)\\,y(t) = B(q)\\,u(t) + e(t)$$\n",
    "\n",
    "Trong đó:\n",
    "- $q^{-1}$: toán tử dịch chuyển sau – $q^{-1}y(t)=y(t-1)$\n",
    "- $A(q) = 1 + a_1q^{-1} + a_2q^{-2}$: đa thức AR\n",
    "- $B(q) = b_1q^{-n_k} + b_2q^{-n_k-1}$: đa thức eXogenous\n",
    "- $e(t)$: nhiễu trắng (white noise)\n",
    "\n",
    "## 2.2 Hệ thống MISO\n",
    "```\n",
    "INPUTS:                          OUTPUT:\n",
    "  Temperature(t)   ─┐\n",
    "  Humidity(t)      ─┤\n",
    "  Light(t)         ─┤──► [ARX(2,2,1)] ──► Soil Moisture(t)\n",
    "  Drip(t)          ─┤\n",
    "  Mist(t)          ─┤\n",
    "  Fan(t)           ─┘\n",
    "```\n",
    "\n",
    "## 2.3 Phương trình đầy đủ ARX(2,2,1)\n",
    "$$\\text{Soil}(t) = a_1 y(t-1) + a_2 y(t-2)$$\n",
    "$$+ b_1 T(t-1) + b_2 T(t-2)$$\n",
    "$$+ b_3 H(t-1) + b_4 H(t-2)$$\n",
    "$$+ b_5 L(t-1) + b_6 L(t-2)$$\n",
    "$$+ b_7 D(t-1) + b_8 D(t-2)$$\n",
    "$$+ b_9 M(t-1) + b_{10} M(t-2)$$\n",
    "$$+ b_{11} F(t-1) + b_{12} F(t-2) + e(t)$$\n",
    "\n",
    "**Tổng: 14 tham số** = 2 (AR) + 12 (6 inputs × 2 lags)\n",
    "\n",
    "## 2.4 Dạng hồi quy tuyến tính\n",
    "$$y(t) = \\varphi(t)^T \\theta + e(t)$$\n",
    "\n",
    "$$\\varphi(t) = [y(t-1),\\, y(t-2),\\, u_1(t-1),\\, u_1(t-2),\\, \\ldots,\\, u_6(t-1),\\, u_6(t-2)]^T \\in \\mathbb{R}^{14}$$\n",
    "\n",
    "## 2.5 Ước lượng Least Squares\n",
    "$$\\hat{\\theta} = (X^TX)^{-1}X^TY$$\n",
    "\n",
    "Tối thiểu hóa: $\\min_{\\theta} \\|Y - X\\theta\\|^2$",
]))

# ── SECTION 3: DATA ───────────────────────────────────────────
cells.append(md(["# 3. Dữ Liệu Greenhouse\n",
    "## 3.1 Tạo dữ liệu tổng hợp (Synthetic Data)\n",
    "Dùng để kiểm tra pipeline khi chưa có dữ liệu thực.\n",
    "Dữ liệu được tạo với **tham số đã biết** để kiểm chứng độ chính xác."]))

cells.append(code([
    "def generate_greenhouse_data(N=3000, T_s=60, seed=42):\n",
    "    \"\"\"\n",
    "    Tạo dữ liệu nhà kính tổng hợp.\n",
    "    \n",
    "    Args:\n",
    "        N:    số mẫu\n",
    "        T_s:  sampling period (giây)\n",
    "        seed: random seed\n",
    "    Returns:\n",
    "        df (DataFrame), true_params (dict)\n",
    "    \"\"\"\n",
    "    np.random.seed(seed)\n",
    "    t = np.arange(N)\n",
    "    period_day = 24 * 3600 / T_s  # samples per day\n",
    "\n",
    "    # ── TRUE PARAMETERS ──────────────────────────────────────\n",
    "    TRUE = {\n",
    "        'a1':  0.87,   'a2': -0.05,\n",
    "        'b_temp':  -0.025, 'b_humi': 0.005,\n",
    "        'b_light': -0.0002,'b_drip': 0.35,\n",
    "        'b_mist':   0.08,  'b_fan': -0.03,\n",
    "    }\n",
    "\n",
    "    # ── INPUTS ───────────────────────────────────────────────\n",
    "    Temp  = 25 + 6*np.sin(2*np.pi*t/period_day) + np.random.normal(0, 1, N)\n",
    "    Humi  = 70 + 15*np.cos(2*np.pi*t/period_day) + np.random.normal(0, 2, N)\n",
    "    Light = np.clip(1200*np.sin(np.pi*(t % period_day)/period_day),\n",
    "                    0, None) + np.random.normal(0, 30, N)\n",
    "    Light = np.clip(Light, 0, 1500)\n",
    "\n",
    "    # Actuators: random switching\n",
    "    Drip = (np.random.random(N) > 0.85).astype(float)   # 15%\n",
    "    Mist = (np.random.random(N) > 0.92).astype(float)   # 8%\n",
    "    Fan  = (np.random.random(N) > 0.70).astype(float)   # 30%\n",
    "\n",
    "    # ── OUTPUT: Soil Moisture ─────────────────────────────────\n",
    "    y = np.zeros(N)\n",
    "    y[0], y[1] = 65.0, 64.8\n",
    "\n",
    "    for i in range(2, N):\n",
    "        y[i] = (TRUE['a1'] * y[i-1] + TRUE['a2'] * y[i-2]\n",
    "                + TRUE['b_temp']  * Temp[i-1]\n",
    "                + TRUE['b_humi']  * Humi[i-1]\n",
    "                + TRUE['b_light'] * Light[i-1]\n",
    "                + TRUE['b_drip']  * Drip[i-1]\n",
    "                + TRUE['b_mist']  * Mist[i-1]\n",
    "                + TRUE['b_fan']   * Fan[i-1]\n",
    "                + np.random.normal(0, 0.25))\n",
    "        y[i] = np.clip(y[i], 0, 100)\n",
    "\n",
    "    df = pd.DataFrame({\n",
    "        'Timestamp':     pd.date_range('2025-01-01', periods=N, freq=f'{T_s}s'),\n",
    "        'Soil_Moisture': y,\n",
    "        'Temperature':   Temp,\n",
    "        'Humidity':      Humi,\n",
    "        'Light':         Light,\n",
    "        'Drip':          Drip,\n",
    "        'Mist':          Mist,\n",
    "        'Fan':           Fan,\n",
    "    })\n",
    "    return df, TRUE\n",
    "\n",
    "\n",
    "df, TRUE_PARAMS = generate_greenhouse_data(N=3000, T_s=60)\n",
    "print(f'Dataset shape: {df.shape}')\n",
    "print(f\"Date range   : {df['Timestamp'].iloc[0]}  →  {df['Timestamp'].iloc[-1]}\")\n",
    "print('\\nTrue parameters used for generation:')\n",
    "for k, v in TRUE_PARAMS.items():\n",
    "    print(f'  {k:12s} = {v:+.4f}')\n",
    "df.head()\n"
]))

cells.append(md(["## 3.2 Thống kê mô tả dữ liệu"]))

cells.append(code([
    "print('=== Descriptive Statistics ===')\n",
    "print(df.describe().round(3).to_string())\n"
]))

cells.append(code([
    "# Visualize all signals\n",
    "fig, axes = plt.subplots(4, 2, figsize=(16, 12))\n",
    "cols  = ['Soil_Moisture', 'Temperature', 'Humidity', 'Light', 'Drip', 'Mist', 'Fan']\n",
    "colors= ['royalblue', 'tomato', 'mediumseagreen', 'darkorange',\n",
    "          'mediumpurple', 'deepskyblue', 'coral']\n",
    "axes_flat = axes.flatten()\n",
    "for i, (col, c) in enumerate(zip(cols, colors)):\n",
    "    axes_flat[i].plot(df[col].values[:500], color=c, linewidth=0.8)\n",
    "    axes_flat[i].set_title(col, fontweight='bold')\n",
    "    axes_flat[i].set_xlabel('Sample index')\n",
    "axes_flat[-1].set_visible(False)\n",
    "fig.suptitle('Greenhouse Sensor Signals (first 500 samples)', fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]))

cells.append(md(["## 3.3 Tải dữ liệu thực (nếu có)\n",
    "```python\n",
    "# Chỉ dùng khi có file CSV thực từ hệ thống nhà kính\n",
    "# df = pd.read_csv('greenhouse_data.csv', parse_dates=['Timestamp'])\n",
    "# df = df.sort_values('Timestamp').dropna().reset_index(drop=True)\n",
    "```\n",
    "\n",
    "**Format yêu cầu:**\n",
    "```\n",
    "Timestamp,Soil_Moisture,Temperature,Humidity,Light,Drip,Mist,Fan\n",
    "2025-01-01 00:00:00,65.2,24.1,72.3,0,0,0,1\n",
    "...\n",
    "```"]))

# ── SECTION 3.4: NOISE FILTERING ──────────────────────────────
cells.append(md([
    "## 3.4 Lọc Nhiễu (Noise Filtering)\n",
    "\n",
    "Dữ liệu cảm biến thực tế thường chứa nhiễu đo lường. Bước này dùng **Savitzky-Golay filter** để làm mịn tín hiệu liên tục "
    "(Temperature, Humidity, Light, Soil_Moisture) trước khi đưa vào mô hình.\n",
    "\n",
    "| Loại tín hiệu | Xử lý |\n",
    "|--------------|-------|\n",
    "| Soil_Moisture, Temperature, Humidity, Light | Savitzky-Golay (window=11, poly=3) |\n",
    "| Drip, Mist, Fan (binary 0/1) | Giữ nguyên – không lọc |\n",
    "\n",
    "> **Tại sao Savitzky-Golay?**  \n",
    "> Bảo toàn các đỉnh (peak) và xu hướng tốt hơn moving average, phù hợp cho tín hiệu sinh học/môi trường.\n",
]))

cells.append(code([
    "from scipy.signal import savgol_filter\n",
    "\n",
    "# ── CONFIG ────────────────────────────────────────────────────\n",
    "FILTER_WINDOW  = 11   # nên là số lẻ; tăng lên để lọc mạnh hơn\n",
    "FILTER_POLY    = 3    # bậc đa thức (3 hoặc 5 là phổ biến)\n",
    "# ⚠️ QUAN TRỌNG: KHÔNG lọc Soil_Moisture (output y)!\n",
    "# Lọc y trước khi fit sẽ làm mất noise dynamics thật → sigma² giả tạo nhỏ, FIT% ảo\n",
    "CONTINUOUS_COLS = ['Temperature', 'Humidity', 'Light']  # CHỈ lọc inputs\n",
    "BINARY_COLS     = ['Drip', 'Mist', 'Fan']   # không lọc binary signals\n",
    "\n",
    "df_filtered = df.copy()\n",
    "\n",
    "for col in CONTINUOUS_COLS:\n",
    "    df_filtered[col] = savgol_filter(\n",
    "        df[col].values,\n",
    "        window_length=FILTER_WINDOW,\n",
    "        polyorder=FILTER_POLY,\n",
    "        mode='nearest'        # xử lý biên\n",
    "    )\n",
    "\n",
    "# ── VISUALIZE: Before vs After filtering ──────────────────────\n",
    "fig, axes = plt.subplots(2, 2, figsize=(16, 8))\n",
    "for ax, col in zip(axes.flatten(), CONTINUOUS_COLS):\n",
    "    n_show = 300\n",
    "    ax.plot(df[col].values[:n_show],          'gray', lw=0.8, alpha=0.6, label='Raw')\n",
    "    ax.plot(df_filtered[col].values[:n_show], 'royalblue', lw=1.5, label='Filtered')\n",
    "    ax.set_title(col, fontweight='bold')\n",
    "    ax.legend(fontsize=9)\n",
    "    ax.set_xlabel('Sample index')\n",
    "\n",
    "fig.suptitle(f'Savitzky-Golay Filter (window={FILTER_WINDOW}, poly={FILTER_POLY}) – first 300 samples',\n",
    "             fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Calculate noise reduction\n",
    "print('=== Noise Reduction ===')\n",
    "for col in CONTINUOUS_COLS:\n",
    "    noise_before = (df[col] - df[col].rolling(5).mean()).std()\n",
    "    noise_after  = (df_filtered[col] - df_filtered[col].rolling(5).mean()).std()\n",
    "    reduction = (1 - noise_after / noise_before) * 100 if noise_before > 0 else 0\n",
    "    print(f'  {col:<15}  noise std: {noise_before:.4f} → {noise_after:.4f}  '\n",
    "          f'({reduction:.1f}% reduction)')\n",
    "\n",
    "print('\\n✅ Filtering done. Using df_filtered for all downstream steps.')\n",
    "df = df_filtered  # Replace raw df\n",
]))

# ── SECTION 3.5: NORMALIZATION ────────────────────────────────
cells.append(md([
    "## 3.5 Chuẩn Hóa Dữ Liệu (Normalization)\n",
    "\n",
    "**Tại sao cần chuẩn hóa?**\n",
    "- `Light` có giá trị ~0–1500 lux, `Drip` chỉ là 0/1 → **chênh lệch scale 1500 lần**\n",
    "- Khi không chuẩn hóa, `Light` sẽ **dominate** regression matrix, làm các tham số nhỏ khó ước lượng\n",
    "- Condition number của X sẽ rất lớn → **không ổn định số học**\n",
    "\n",
    "**Phương pháp: Min-Max Scaling** (fit trên train, áp lên val):\n",
    "$$x_{norm} = \\frac{x - x_{min}}{x_{max} - x_{min}} \\in [0, 1]$$\n",
    "\n",
    "> ⚠️ **Quan trọng:** Fit scaler TRÊN TRAIN rồi apply lên VAL (tránh data leakage)\n",
]))

cells.append(code([
    "# ── MIN-MAX SCALER ───────────────────────────────────────────\n",
    "ALL_FEATURE_COLS = ['Soil_Moisture', 'Temperature', 'Humidity', 'Light']\n",
    "# Binary cols (Drip, Mist, Fan) đã ở thang 0-1, không cần scale\n",
    "\n",
    "# Fit on training portion (before split)\n",
    "N_total = len(df)\n",
    "TRAIN_RATIO = 0.70\n",
    "n_train = int(N_total * TRAIN_RATIO)\n",
    "\n",
    "scaler_min = df.iloc[:n_train][ALL_FEATURE_COLS].min()\n",
    "scaler_max = df.iloc[:n_train][ALL_FEATURE_COLS].max()\n",
    "scaler_range = scaler_max - scaler_min\n",
    "\n",
    "def normalize(df_in, cols=ALL_FEATURE_COLS):\n",
    "    df_out = df_in.copy()\n",
    "    df_out[cols] = (df_in[cols] - scaler_min) / scaler_range\n",
    "    return df_out\n",
    "\n",
    "def denormalize_y(y_norm):\n",
    "    \"\"\"Chuyển soil moisture từ normalized về đơn vị %\"\"\"\n",
    "    return y_norm * scaler_range['Soil_Moisture'] + scaler_min['Soil_Moisture']\n",
    "\n",
    "df_norm = normalize(df)\n",
    "\n",
    "# ── Show before/after ─────────────────────────────────────────\n",
    "print('=== Scaling Info (fit on training set) ===')\n",
    "for col in ALL_FEATURE_COLS:\n",
    "    print(f'  {col:<15}  min={scaler_min[col]:.3f}  max={scaler_max[col]:.3f}  '\n",
    "          f'range={scaler_range[col]:.3f}')\n",
    "\n",
    "print('\\n=== Normalized Statistics (should be ≈ [0, 1]) ===')\n",
    "print(df_norm[ALL_FEATURE_COLS + BINARY_COLS].describe().round(3).to_string())\n",
    "\n",
    "# Condition number comparison\n",
    "from numpy.linalg import cond, matrix_rank\n",
    "\n",
    "def quick_cond(df_in, na=2, nb=2, nk=1):\n",
    "    n = int(len(df_in) * TRAIN_RATIO)\n",
    "    df_tr = df_in.iloc[:n]\n",
    "    X, _ = build_regression_matrix(df_tr, na, nb, nk) if 'build_regression_matrix' in dir() else (None, None)\n",
    "    return cond(X.T @ X) if X is not None else float('nan')\n",
    "\n",
    "print('\\n💡 Condition number will be computed after build_regression_matrix is defined (Section 4).')\n",
    "print('✅ Normalization done. Using df_norm for all downstream steps.')\n",
    "df = df_norm  # Replace filtered df with normalized df\n",
]))

# ── SECTION 4: SPLIT + REGRESSION MATRIX ──────────────────────
cells.append(md(["# 4. Phân Chia Dữ Liệu & Xây Dựng Ma Trận Hồi Quy\n",
    "## 4.1 Train / Validation Split\n",
    "Dùng **phân chia tuần tự theo thời gian** (không shuffle) để tránh data leakage.\n",
    "```\n",
    "┌───────────────────────────────────────────────────┐\n",
    "│              Full Dataset (N = 3000)               │\n",
    "│  DS1 – Training (70%)  │  DS2 – Validation (30%)  │\n",
    "│       2100 samples      │       900 samples        │\n",
    "└───────────────────────────────────────────────────┘\n",
    "```"]))

cells.append(code([
    "# ── CONFIG ──────────────────────────────────────────────────\n",
    "NA = 2   # AR order\n",
    "NB = 2   # input order\n",
    "NK = 1   # input delay\n",
    "TRAIN_RATIO = 0.70\n",
    "\n",
    "# ── SPLIT ────────────────────────────────────────────────────\n",
    "N_total = len(df)\n",
    "n_train = int(N_total * TRAIN_RATIO)\n",
    "df_train = df.iloc[:n_train].copy()\n",
    "df_val   = df.iloc[n_train:].copy().reset_index(drop=True)\n",
    "\n",
    "print(f'Total samples : {N_total}')\n",
    "print(f'Training (DS1): {len(df_train)} samples  ({TRAIN_RATIO*100:.0f}%)')\n",
    "print(f'Validation(DS2): {len(df_val)} samples  ({(1-TRAIN_RATIO)*100:.0f}%)')\n"
]))

cells.append(md(["## 4.2 Xây dựng Regression Matrix X và Output Vector Y\n",
    "\n",
    "$$X = \\begin{bmatrix} \\varphi(3)^T \\\\ \\varphi(4)^T \\\\ \\vdots \\\\ \\varphi(N)^T \\end{bmatrix} \\in \\mathbb{R}^{(N-2) \\times 14}, \\quad Y = \\begin{bmatrix} y(3) \\\\ y(4) \\\\ \\vdots \\\\ y(N) \\end{bmatrix} \\in \\mathbb{R}^{N-2}$$"]))

cells.append(code([
    "INPUT_COLS = ['Temperature', 'Humidity', 'Light', 'Drip', 'Mist', 'Fan']\n",
    "OUTPUT_COL = 'Soil_Moisture'\n",
    "\n",
    "\n",
    "def build_regression_matrix(df, na=2, nb=2, nk=1,\n",
    "                             input_cols=INPUT_COLS, output_col=OUTPUT_COL):\n",
    "    \"\"\"\n",
    "    Xây dựng ma trận hồi quy X và vector Y cho ARX(na, nb, nk).\n",
    "\n",
    "    Returns:\n",
    "        X : (N_eff × n_params) regression matrix\n",
    "        Y : (N_eff,)            output vector\n",
    "    \"\"\"\n",
    "    y = df[output_col].values\n",
    "    Us = [df[c].values for c in input_cols]\n",
    "    n_inputs = len(Us)\n",
    "\n",
    "    max_lag = max(na, nb + nk - 1)\n",
    "    N       = len(y)\n",
    "    N_eff   = N - max_lag\n",
    "    n_params = na + n_inputs * nb\n",
    "\n",
    "    X = np.zeros((N_eff, n_params))\n",
    "    Y = np.zeros(N_eff)\n",
    "\n",
    "    for i in range(N_eff):\n",
    "        t   = i + max_lag\n",
    "        row = []\n",
    "        # AR terms\n",
    "        for lag in range(1, na + 1):\n",
    "            row.append(y[t - lag])\n",
    "        # eXogenous terms\n",
    "        for u in Us:\n",
    "            for lag in range(nk, nk + nb):\n",
    "                row.append(u[t - lag])\n",
    "        X[i] = row\n",
    "        Y[i] = y[t]\n",
    "\n",
    "    return X, Y\n",
    "\n",
    "\n",
    "X_train, Y_train = build_regression_matrix(df_train, NA, NB, NK)\n",
    "X_val,   Y_val   = build_regression_matrix(df_val,   NA, NB, NK)\n",
    "\n",
    "print(f'X_train shape : {X_train.shape}  (N_eff × n_params)')\n",
    "print(f'Y_train shape : {Y_train.shape}')\n",
    "print(f'X_val   shape : {X_val.shape}')\n",
    "\n",
    "# Check rank\n",
    "rank = np.linalg.matrix_rank(X_train)\n",
    "cond = np.linalg.cond(X_train.T @ X_train)\n",
    "print(f'\\nRank of X_train  : {rank} / {X_train.shape[1]}  (phải bằng nhau)')\n",
    "print(f'Condition number : {cond:.2f}  (nên < 1e6)')\n",
    "\n",
    "# Column names\n",
    "PARAM_NAMES = (['a1','a2'] +\n",
    "               [f'b_{c}_{l}' for c in INPUT_COLS for l in range(1, NB+1)])\n",
    "print(f'\\nParameter names ({len(PARAM_NAMES)} total):')\n",
    "print(PARAM_NAMES)\n"
]))

cells.append(code([
    "# Correlation heatmap of regression matrix\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "corr = np.corrcoef(X_train.T)\n",
    "fig, ax = plt.subplots(figsize=(10, 8))\n",
    "im = ax.imshow(np.abs(corr), cmap='RdYlGn_r', vmin=0, vmax=1)\n",
    "ax.set_xticks(range(len(PARAM_NAMES)))\n",
    "ax.set_yticks(range(len(PARAM_NAMES)))\n",
    "ax.set_xticklabels(PARAM_NAMES, rotation=90, fontsize=9)\n",
    "ax.set_yticklabels(PARAM_NAMES, fontsize=9)\n",
    "plt.colorbar(im, ax=ax, label='|Correlation|')\n",
    "ax.set_title('Correlation Matrix of Regressors (|corr|)', fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "print('High correlation (>0.8) may indicate multicollinearity issues.')\n"
]))

# ── SECTION 5: PARAMETER ESTIMATION ───────────────────────────
cells.append(md(["# 5. Ước Lượng Tham Số – Least Squares\n",
    "## 5.1 Ordinary Least Squares (OLS)\n",
    "$$\\hat{\\theta} = (X^TX)^{-1}X^TY$$\n",
    "\n",
    "**Tính chất:** $\\hat{\\theta}$ là BLUE (Best Linear Unbiased Estimator) theo định lý Gauss-Markov.\n",
    "\n",
    "**Uncertainty:** $\\text{Cov}(\\hat{\\theta}) = \\sigma^2 (X^TX)^{-1}$"]))

cells.append(code([
    "def estimate_ols(X, Y):\n",
    "    \"\"\"\n",
    "    Ordinary Least Squares estimation.\n",
    "    Returns: theta, cov_matrix, sigma2\n",
    "    \"\"\"\n",
    "    # lstsq is numerically more stable than pinv\n",
    "    theta, _, _, _ = np.linalg.lstsq(X, Y, rcond=None)\n",
    "\n",
    "    N, k   = X.shape\n",
    "    Y_pred = X @ theta\n",
    "    resid  = Y - Y_pred\n",
    "    sigma2 = np.dot(resid, resid) / (N - k)   # unbiased estimator\n",
    "    cov    = sigma2 * np.linalg.pinv(X.T @ X)\n",
    "\n",
    "    return theta, cov, sigma2\n",
    "\n",
    "\n",
    "theta_hat, cov_hat, sigma2_hat = estimate_ols(X_train, Y_train)\n",
    "std_hat = np.sqrt(np.diag(cov_hat))\n",
    "\n",
    "# ── DENORMALIZE THETA về không gian gốc ─────────────────────\n",
    "# Trong normalized space: y_n = a*y_n_lag + b_n*u_n_lag\n",
    "# AR coefs (a1, a2) KHÔNG đổi (ratio y/y → scale cancel)\n",
    "# b coefs: b_orig = b_norm * (y_range / u_range)\n",
    "# Binary inputs (Drip, Mist, Fan) không được normalize → u_range = 1\n",
    "# → b_binary_orig = b_norm * y_range\n",
    "\n",
    "# Build scale vector cho từng tham số\n",
    "theta_scale = []\n",
    "for name in PARAM_NAMES:\n",
    "    if name.startswith('a'):   # AR terms: scale = 1\n",
    "        theta_scale.append(1.0)\n",
    "    else:                       # b_InputName_lag\n",
    "        # tên dạng 'b_Temperature_1' → input = 'Temperature'\n",
    "        input_name = '_'.join(name.split('_')[1:-1])\n",
    "        if input_name in scaler_range.index:  # input được normalize\n",
    "            u_rng = float(scaler_range[input_name])\n",
    "            theta_scale.append(float(scaler_range['Soil_Moisture']) / u_rng)\n",
    "        else:                                  # binary: range = 1\n",
    "            theta_scale.append(float(scaler_range['Soil_Moisture']))\n",
    "\n",
    "theta_orig = theta_hat * np.array(theta_scale)  # theta trong đơn vị gốc (%)\n",
    "sigma2_orig = sigma2_hat * float(scaler_range['Soil_Moisture'])**2  # var trong đơn vị %\n",
    "\n",
    "print(f'Estimated noise σ (normalized): {np.sqrt(sigma2_hat):.6f}')\n",
    "print(f'Estimated noise σ (original %): {np.sqrt(sigma2_orig):.4f} %  [true ≈ 0.25 %]\\n')\n",
    "\n",
    "print(f'{\"Param\":<15} {\"θ̂_norm\":>12}  {\"θ̂_orig (%)\":>13}  [TRUE (if known)]')\n",
    "print('-' * 70)\n",
    "\n",
    "# TRUE_PARAMS ở space gốc (%) – so sánh trực tiếp với theta_orig\n",
    "true_ref = {\n",
    "    'a1': TRUE_PARAMS['a1'],    'a2': TRUE_PARAMS['a2'],\n",
    "    'b_Drip_1':  TRUE_PARAMS['b_drip'],\n",
    "    'b_Temperature_1': TRUE_PARAMS['b_temp'],\n",
    "}\n",
    "\n",
    "for name, th_n, th_o in zip(PARAM_NAMES, theta_hat, theta_orig):\n",
    "    ref   = true_ref.get(name, float('nan'))\n",
    "    ref_s = f'{ref:+.4f}' if not np.isnan(ref) else '  —'\n",
    "    match = ' ✅' if (not np.isnan(ref) and abs(th_o - ref) < 0.05) else (' ⚠️' if not np.isnan(ref) else '')\n",
    "    print(f'{name:<15} {th_n:+12.6f}  {th_o:+13.6f}  {ref_s}{match}')\n"
]))

cells.append(code([
    "# Bar chart of estimated parameters\n",
    "fig, ax = plt.subplots(figsize=(14, 5))\n",
    "x_pos = np.arange(len(PARAM_NAMES))\n",
    "colors_bar = ['royalblue' if v >= 0 else 'tomato' for v in theta_hat]\n",
    "bars = ax.bar(x_pos, theta_hat, color=colors_bar, edgecolor='black', linewidth=0.7)\n",
    "ax.errorbar(x_pos, theta_hat, yerr=1.96*std_hat, fmt='none',\n",
    "            color='black', capsize=5, linewidth=1.5)\n",
    "ax.axhline(0, color='black', linewidth=0.8, linestyle='--')\n",
    "ax.set_xticks(x_pos)\n",
    "ax.set_xticklabels(PARAM_NAMES, rotation=45, ha='right', fontsize=10)\n",
    "ax.set_ylabel('Parameter value θ̂')\n",
    "ax.set_title('ARX(2,2,1) Estimated Parameters with 95% Confidence Intervals',\n",
    "             fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]))

# ── SECTION 6: PREDICTION ────────────────────────────────────
cells.append(md(["# 6. Dự Đoán\n",
    "## 6.1 One-Step-Ahead Prediction\n",
    "Dùng giá trị **thực** của y(t-1), y(t-2) khi dự đoán:\n",
    "$$\\hat{y}(t|t-1) = \\varphi(t)^T \\hat{\\theta}$$\n",
    "\n",
    "## 6.2 Free-Run Simulation (Multi-step)\n",
    "Thay y(t-1), y(t-2) bằng **giá trị dự đoán** trước đó – phản ánh đúng hơn khả năng mô hình."]))

cells.append(code([
    "# ── ONE-STEP PREDICTION ──────────────────────────────────────\n",
    "Y_train_pred = X_train @ theta_hat\n",
    "Y_val_pred   = X_val   @ theta_hat\n",
    "\n",
    "\n",
    "# ── FREE-RUN SIMULATION ──────────────────────────────────────\n",
    "def simulate_arx(df_sim, theta, na=NA, nb=NB, nk=NK,\n",
    "                 input_cols=INPUT_COLS, output_col=OUTPUT_COL):\n",
    "    \"\"\"\n",
    "    Multi-step (free-run) simulation.  Uses predicted y values\n",
    "    to feed back into the AR part.\n",
    "    \"\"\"\n",
    "    y = df_sim[output_col].values.copy()  # ground truth (used as init)\n",
    "    Us = [df_sim[c].values for c in input_cols]\n",
    "    N  = len(y)\n",
    "    max_lag = max(na, nb + nk - 1)\n",
    "    y_sim = y.copy()\n",
    "\n",
    "    for t in range(max_lag, N):\n",
    "        row = []\n",
    "        for lag in range(1, na + 1):\n",
    "            row.append(y_sim[t - lag])   # use simulated (not true) y\n",
    "        for u in Us:\n",
    "            for lag in range(nk, nk + nb):\n",
    "                row.append(u[t - lag])\n",
    "        y_sim[t] = np.dot(row, theta)\n",
    "\n",
    "    return y_sim[max_lag:], y[max_lag:]\n",
    "\n",
    "\n",
    "Y_sim, Y_true_sim = simulate_arx(df_val, theta_hat)\n",
    "\n",
    "print(f'One-step prediction on validation: {len(Y_val_pred)} samples')\n",
    "print(f'Free-run simulation  on validation: {len(Y_sim)} samples')\n"
]))

cells.append(code([
    "# Plot prediction vs actual (validation set, first 300 samples)\n",
    "n_plot = min(300, len(Y_val))\n",
    "t_plot = np.arange(n_plot)\n",
    "\n",
    "fig, axes = plt.subplots(2, 1, figsize=(14, 8))\n",
    "\n",
    "# One-step\n",
    "axes[0].plot(t_plot, Y_val[:n_plot],      'b',  label='Actual',          lw=1.2)\n",
    "axes[0].plot(t_plot, Y_val_pred[:n_plot], 'r--',label='1-step Prediction',lw=1.2)\n",
    "axes[0].set_ylabel('Soil Moisture (%)')\n",
    "axes[0].set_title('One-Step-Ahead Prediction – Validation Set', fontweight='bold')\n",
    "axes[0].legend()\n",
    "\n",
    "# Free-run\n",
    "n_sim = min(n_plot, len(Y_sim))\n",
    "axes[1].plot(np.arange(n_sim), Y_true_sim[:n_sim], 'b',  label='Actual',           lw=1.2)\n",
    "axes[1].plot(np.arange(n_sim), Y_sim[:n_sim],      'm--',label='Simulation (free-run)', lw=1.2)\n",
    "axes[1].set_xlabel('Sample index')\n",
    "axes[1].set_ylabel('Soil Moisture (%)')\n",
    "axes[1].set_title('Free-Run Simulation – Validation Set', fontweight='bold')\n",
    "axes[1].legend()\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]))

# ── SECTION 7: EVALUATION ────────────────────────────────────
cells.append(md(["# 7. Đánh Giá Mô Hình\n",
    "| Metric | Công thức | Ý nghĩa |\n",
    "|--------|-----------|--------|\n",
    "| **RMSE** | $\\sqrt{\\frac{1}{N}\\sum(y-\\hat{y})^2}$ | Sai số trung bình bình phương (cùng đơn vị với y) |\n",
    "| **MAE**  | $\\frac{1}{N}\\sum|y-\\hat{y}|$ | Sai số tuyệt đối trung bình |\n",
    "| **FIT**  | $100(1-\\|y-\\hat{y}\\|/\\|y-\\bar{y}\\|)$ | % khớp (100% = hoàn hảo) |\n",
    "| **R²**   | $1 - SS_{res}/SS_{tot}$ | Hệ số xác định |\n",
    "| **AIC**  | $N\\ln(\\hat{\\sigma}^2) + 2k$ | Tiêu chuẩn Akaike (nhỏ hơn = tốt hơn) |\n",
    "| **BIC**  | $N\\ln(\\hat{\\sigma}^2) + k\\ln(N)$ | Tiêu chuẩn Bayes (phạt complexity mạnh hơn) |"]))

cells.append(code([
    "def compute_metrics(Y_true, Y_pred, n_params):\n",
    "    \"\"\"Tính đầy đủ các metrics đánh giá mô hình.\"\"\"\n",
    "    N        = len(Y_true)\n",
    "    resid    = Y_true - Y_pred\n",
    "    ss_res   = np.dot(resid, resid)\n",
    "    ss_tot   = np.dot(Y_true - Y_true.mean(), Y_true - Y_true.mean())\n",
    "    sigma2   = ss_res / N\n",
    "\n",
    "    rmse = np.sqrt(ss_res / N)\n",
    "    mae  = np.mean(np.abs(resid))\n",
    "    fit  = 100 * (1 - np.linalg.norm(resid) / np.linalg.norm(Y_true - Y_true.mean()))\n",
    "    r2   = 1 - ss_res / ss_tot\n",
    "    aic  = N * np.log(sigma2 + 1e-12) + 2 * n_params\n",
    "    bic  = N * np.log(sigma2 + 1e-12) + n_params * np.log(N)\n",
    "\n",
    "    return dict(RMSE=rmse, MAE=mae, FIT=fit, R2=r2, AIC=aic, BIC=bic)\n",
    "\n",
    "\n",
    "n_params = len(theta_hat)\n",
    "\n",
    "# ── DENORMALIZE về đơn vị % trước khi tính metrics ──────────────\n",
    "# Lý do: OLS chạy trên normalized data → predictions ở normalized space\n",
    "# Metrics (nhất là RMSE, MAE) phải ở original space để có nghĩa vật lý\n",
    "Y_train_predO = denormalize_y(Y_train_pred)   # predictions → %\n",
    "Y_train_trueO = denormalize_y(Y_train)         # ground truth → %\n",
    "Y_val_predO   = denormalize_y(Y_val_pred)\n",
    "Y_val_trueO   = denormalize_y(Y_val)\n",
    "Y_sim_predO   = denormalize_y(Y_sim)\n",
    "Y_sim_trueO   = denormalize_y(Y_true_sim)\n",
    "\n",
    "print('=== Sanity check (should be in ~20-80% range) ===')\n",
    "print(f'  Y_val_trueO: min={Y_val_trueO.min():.2f}%  max={Y_val_trueO.max():.2f}%')\n",
    "print(f'  Y_val_predO: min={Y_val_predO.min():.2f}%  max={Y_val_predO.max():.2f}%')\n",
    "\n",
    "m_train  = compute_metrics(Y_train_trueO, Y_train_predO, n_params)\n",
    "m_val    = compute_metrics(Y_val_trueO,   Y_val_predO,   n_params)\n",
    "m_sim    = compute_metrics(Y_sim_trueO,   Y_sim_predO,   n_params)\n",
    "\n",
    "print(f\"\\n=== Metrics in ORIGINAL space (%) ===\")\n",
    "print(f\"{'Metric':<8} | {'DS1 Train':>12} | {'DS2 Val (1-step)':>16} | {'DS2 Val (sim)':>14} | Target\")\n",
    "print('-' * 72)\n",
    "targets = {'RMSE':'< 2.0 %', 'MAE':'< 1.5 %', 'FIT':'> 80 %',\n",
    "           'R2':'> 0.90', 'AIC':'minimize', 'BIC':'minimize'}\n",
    "for k in ['RMSE','MAE','FIT','R2','AIC','BIC']:\n",
    "    unit = ' %' if k in ('FIT','RMSE','MAE') else ''\n",
    "    print(f'{k:<8} | {m_train[k]:>12.4f}{unit} | {m_val[k]:>14.4f}{unit} | {m_sim[k]:>12.4f}{unit}  {targets[k]}')\n",
]))

cells.append(code([
    "# Radar chart – model performance summary\n",
    "from matplotlib.patches import FancyArrowPatch\n",
    "\n",
    "metrics_disp = {\n",
    "    'FIT (%)':  m_val['FIT'] / 100,\n",
    "    'R\u00b2':       m_val['R2'],\n",
    "    '1-NRMSE':  1 - m_val['RMSE'] / (Y_val_trueO.max() - Y_val_trueO.min()),\n",
    "    '1-MAE%':   1 - m_val['MAE']  / (Y_val_trueO.max() - Y_val_trueO.min()),\n",
    "}\n",
    "\n",
    "labels = list(metrics_disp.keys())\n",
    "vals   = list(metrics_disp.values())\n",
    "N_r    = len(labels)\n",
    "angles = np.linspace(0, 2*np.pi, N_r, endpoint=False).tolist()\n",
    "vals  += vals[:1];  angles += angles[:1]\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(polar=True))\n",
    "ax.plot(angles, vals, 'o-', color='royalblue', linewidth=2)\n",
    "ax.fill(angles, vals, alpha=0.25, color='royalblue')\n",
    "ax.set_thetagrids(np.degrees(angles[:-1]), labels)\n",
    "ax.set_ylim(0, 1)\n",
    "ax.set_title('Model Performance Radar\\n(Validation Set)', fontweight='bold', pad=20)\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]))

# ── SECTION 8: RESIDUALS ──────────────────────────────────────
cells.append(md(["# 8. Phân Tích Phần Dư (Residual Analysis)\n",
    "Phần dư $e(t) = y(t) - \\hat{y}(t)$ phải thỏa:\n",
    "1. **White noise** – không có autocorrelation\n",
    "2. **Phân phối chuẩn** – zero mean, constant variance\n",
    "3. **Uncorrelated with inputs** – nếu còn tương quan → mô hình chưa đủ input"]))

cells.append(code([
    "# Residuals in ORIGINAL space (%) \u2013 \u0111\u01a1n v\u1ecb v\u1eadt l\u00fd c\u00f3 ngh\u0129a\n",
    "residuals = Y_val_trueO - Y_val_predO\n",
    "N_res = len(residuals)\n",
    "\n",
    "fig = plt.figure(figsize=(16, 12))\n",
    "gs  = gridspec.GridSpec(2, 3, figure=fig)\n",
    "\n",
    "# 1. Residuals over time\n",
    "ax1 = fig.add_subplot(gs[0, :])\n",
    "ax1.plot(residuals, 'g', linewidth=0.7, alpha=0.8)\n",
    "ax1.axhline(0, color='k', linewidth=1, linestyle='--')\n",
    "ax1.fill_between(range(N_res), residuals, 0, alpha=0.3, color='green')\n",
    "ax1.set(xlabel='Sample', ylabel='Residual (%)', title='Residuals over Time')\n",
    "\n",
    "# 2. Histogram + Normal fit\n",
    "ax2 = fig.add_subplot(gs[1, 0])\n",
    "ax2.hist(residuals, bins=50, density=True, color='purple', alpha=0.6, edgecolor='white')\n",
    "x_r = np.linspace(residuals.min(), residuals.max(), 200)\n",
    "mu_r, sd_r = residuals.mean(), residuals.std()\n",
    "ax2.plot(x_r, stats.norm.pdf(x_r, mu_r, sd_r), 'r-', lw=2, label=f'N({mu_r:.3f},{sd_r:.3f})')\n",
    "ax2.set(xlabel='Residual', ylabel='Density', title='Residual Distribution')\n",
    "ax2.legend()\n",
    "\n",
    "# 3. Q-Q plot\n",
    "ax3 = fig.add_subplot(gs[1, 1])\n",
    "stats.probplot(residuals, plot=ax3)\n",
    "ax3.set_title('Q-Q Plot (Normality Check)')\n",
    "\n",
    "# 4. Autocorrelation of residuals\n",
    "ax4 = fig.add_subplot(gs[1, 2])\n",
    "max_lag_acf = 40\n",
    "acf = [np.corrcoef(residuals[:-k], residuals[k:])[0,1] for k in range(1, max_lag_acf+1)]\n",
    "conf = 1.96 / np.sqrt(N_res)\n",
    "ax4.bar(range(1, max_lag_acf+1), acf, color='steelblue', edgecolor='white', width=0.8)\n",
    "ax4.axhline( conf, color='r', linestyle='--', lw=1.5, label='95% CI')\n",
    "ax4.axhline(-conf, color='r', linestyle='--', lw=1.5)\n",
    "ax4.set(xlabel='Lag', ylabel='ACF', title='Residual Autocorrelation')\n",
    "ax4.legend()\n",
    "\n",
    "plt.suptitle('Residual Analysis – Validation Set', fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]))

cells.append(code([
    "# Statistical tests\n",
    "from scipy.stats import shapiro, normaltest\n",
    "\n",
    "print('=== STATISTICAL TESTS ON RESIDUALS ===')\n",
    "\n",
    "# Normality\n",
    "_, p_sw  = shapiro(residuals[:1000])\n",
    "_, p_dag = normaltest(residuals)\n",
    "print(f'\\n1. Normality:')\n",
    "print(f'   Shapiro-Wilk   p = {p_sw:.4f}  → {\"NORMAL ✅\" if p_sw>0.05 else \"NOT normal ⚠️\"}')\n",
    "print(f'   D'Agostino-K²  p = {p_dag:.4f}  → {\"NORMAL ✅\" if p_dag>0.05 else \"NOT normal ⚠️\"}')\n",
    "\n",
    "# Ljung-Box test\n",
    "try:\n",
    "    from statsmodels.stats.diagnostic import acorr_ljungbox\n",
    "    lb = acorr_ljungbox(residuals, lags=20, return_df=True)\n",
    "    lb_fail = lb[lb['lb_pvalue'] < 0.05]\n",
    "    print(f'\\n2. Ljung-Box (H0: no autocorrelation):')\n",
    "    if lb_fail.empty:\n",
    "        print('   PASSED ✅ – residuals appear to be white noise')\n",
    "    else:\n",
    "        print(f'   FAILED ⚠️ – autocorrelation at lags: {lb_fail.index.tolist()}')\n",
    "        print('   → Consider increasing na')\n",
    "except ImportError:\n",
    "    print('   statsmodels not installed – skip Ljung-Box')\n",
    "\n",
    "# Cross-correlation with inputs\n",
    "print(f'\\n3. Cross-correlation residuals vs inputs (|cc| < 0.1 is OK):')\n",
    "n_min = min(N_res, len(df_val) - max(NA, NB + NK - 1))\n",
    "for col in INPUT_COLS:\n",
    "    u_vals = df_val[col].values[max(NA, NB+NK-1): max(NA, NB+NK-1) + n_min]\n",
    "    cc = np.corrcoef(residuals[:n_min], u_vals[:n_min])[0, 1]\n",
    "    status = '✅' if abs(cc) < 0.1 else '⚠️'\n",
    "    print(f'   corr(e, {col:<12}) = {cc:+.4f}  {status}')\n",
    "\n",
    "print(f'\\n4. Mean of residuals: {mu_r:.6f}  (target: ~0)')\n",
    "print(f'5. Std  of residuals: {sd_r:.6f} %')\n"
]))

# ── SECTION 9: MODEL SELECTION ─────────────────────────────────
cells.append(md(["# 9. Lựa Chọn Bậc Mô Hình (Model Order Selection)\n",
    "So sánh các cấu trúc ARX(na, nb, nk) khác nhau theo **AIC** và **FIT** trên validation set."]))

cells.append(code([
    "import itertools\n",
    "\n",
    "def model_selection_search(df_tr, df_vl,\n",
    "                            na_list=[1,2,3],\n",
    "                            nb_list=[1,2,3],\n",
    "                            nk_list=[1,2]):\n",
    "    results = []\n",
    "    combos = list(itertools.product(na_list, nb_list, nk_list))\n",
    "    print(f'Testing {len(combos)} model structures...')\n",
    "\n",
    "    for na, nb, nk in combos:\n",
    "        try:\n",
    "            Xt, Yt = build_regression_matrix(df_tr, na, nb, nk)\n",
    "            Xv, Yv = build_regression_matrix(df_vl, na, nb, nk)\n",
    "            th, _, _ = estimate_ols(Xt, Yt)\n",
    "            Yv_p = Xv @ th\n",
    "            n_p  = len(th)\n",
    "            m    = compute_metrics(Yv, Yv_p, n_p)\n",
    "            results.append({'na':na,'nb':nb,'nk':nk,'n_params':n_p, **m})\n",
    "        except Exception:\n",
    "            pass\n",
    "\n",
    "    res_df = pd.DataFrame(results).sort_values('AIC').reset_index(drop=True)\n",
    "    return res_df\n",
    "\n",
    "\n",
    "sel_df = model_selection_search(df_train, df_val,\n",
    "                                 na_list=[1,2,3],\n",
    "                                 nb_list=[1,2,3],\n",
    "                                 nk_list=[1,2])\n",
    "\n",
    "print('\\n=== Model Selection Results (sorted by AIC) ===')\n",
    "display_cols = ['na','nb','nk','n_params','RMSE','FIT','R2','AIC','BIC']\n",
    "print(sel_df[display_cols].head(10).to_string(index=False, float_format='{:.4f}'.format))\n",
    "print(f'\\n✅ Best model by AIC: ARX({sel_df.iloc[0].na:.0f}, '\n",
    "      f'{sel_df.iloc[0].nb:.0f}, {sel_df.iloc[0].nk:.0f})')\n"
]))

cells.append(code([
    "# Pareto plot: FIT vs n_params\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "sc = axes[0].scatter(sel_df['n_params'], sel_df['FIT'], c=sel_df['AIC'],\n",
    "                      cmap='RdYlGn_r', s=80, edgecolors='black', linewidth=0.5)\n",
    "plt.colorbar(sc, ax=axes[0], label='AIC')\n",
    "axes[0].set(xlabel='Number of parameters', ylabel='FIT (%)',\n",
    "             title='Pareto: Complexity vs Accuracy')\n",
    "# Annotate best\n",
    "best = sel_df.iloc[0]\n",
    "axes[0].annotate(f\"ARX({best.na:.0f},{best.nb:.0f},{best.nk:.0f})\",\n",
    "                  xy=(best.n_params, best.FIT), fontsize=10, color='darkgreen',\n",
    "                  xytext=(best.n_params+0.5, best.FIT-2))\n",
    "\n",
    "# AIC bar for top-10\n",
    "top10 = sel_df.head(10)\n",
    "labels_10 = [f\"({r.na:.0f},{r.nb:.0f},{r.nk:.0f})\" for _, r in top10.iterrows()]\n",
    "colors_10 = plt.cm.RdYlGn_r(np.linspace(0, 0.8, len(top10)))\n",
    "axes[1].barh(labels_10[::-1], top10['AIC'].values[::-1],\n",
    "              color=colors_10, edgecolor='black', linewidth=0.5)\n",
    "axes[1].set(xlabel='AIC', title='Top-10 Models by AIC (lower = better)')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]))

# ── SECTION 10: CONCLUSION ────────────────────────────────────
cells.append(md(["# 10. Kết Luận & Hướng Mở Rộng\n",
    "## 10.1 Tổng kết ARX(2,2,1)\n",
    "\n",
    "| Tiêu chí | Kết quả |\n",
    "|----------|---------|\n",
    "| Số tham số | 14 |\n",
    "| Phương pháp | Ordinary Least Squares |\n",
    "| Dữ liệu | 3000 mẫu (T_s = 60s) |\n",
    "| Hiệu suất | FIT > 90% (synthetic) |\n",
    "\n",
    "## 10.2 Mô hình nâng cao (so sánh)\n",
    "\n",
    "| Mô hình | Đặc điểm | Khi nào dùng |\n",
    "|---------|-----------|-------------|\n",
    "| **ARX** | Tuyến tính, OLS | Baseline, điều khiển cơ bản |\n",
    "| **ARMAX** | Thêm MA noise model | Khi residuals có autocorrelation |\n",
    "| **OE (Output Error)** | Tách noise model | Khi measurement noise lớn |\n",
    "| **NARX** | Phi tuyến | Khi FIT < 70% với ARX |\n",
    "| **LSTM/GRU** | Deep learning | Big data, > 50K samples |\n",
    "\n",
    "## 10.3 Pipeline hoàn chỉnh để sử dụng thực tế\n",
    "\n",
    "```\n",
    "Thu thập dữ liệu\n",
    "    → Làm sạch (dropna, outliers)\n",
    "    → Kiểm tra persistent excitation\n",
    "    → Chọn bậc mô hình (AIC/BIC)\n",
    "    → Ước lượng tham số (OLS)\n",
    "    → Kiểm tra residuals (white noise?)\n",
    "    → Đánh giá trên DS2 (FIT > 80%?)\n",
    "    → Tích hợp vào bộ điều khiển (MPC)\n",
    "```\n",
    "\n",
    "## 10.4 Tích hợp MPC (Model Predictive Control)\n",
    "\n",
    "ARX model là cơ sở cho MPC:\n",
    "$$\\min_{u} \\sum_{k=1}^{H_p} (\\hat{y}(t+k) - y_{ref})^2 + \\lambda \\sum_{k=0}^{H_c-1} (\\Delta u(t+k))^2$$\n",
    "\n",
    "- $H_p$: prediction horizon\n",
    "- $H_c$: control horizon  \n",
    "- $\\lambda$: control weight (tradeoff giữa tracking và effort)\n",
    "\n",
    "---\n",
    "*Tài liệu này được tạo dựa trên ARX_Model_Documentation.md*  \n",
    "*Phiên bản: 1.0 | 2026-03-20*"]))

cells.append(code([
    "# Save estimated parameters to file for later use\n",
    "import json\n",
    "\n",
    "# ── Denormalize metrics về không gian gốc ─────────────────\n",
    "# 1-step prediction trong original space (denormalize predictions)\n",
    "Y_train_orig = denormalize_y(Y_train_pred)\n",
    "Y_train_true_orig = denormalize_y(Y_train)\n",
    "Y_val_orig   = denormalize_y(Y_val_pred)\n",
    "Y_val_true_orig = denormalize_y(Y_val)\n",
    "Y_sim_orig   = denormalize_y(Y_sim)\n",
    "Y_sim_true_orig = denormalize_y(Y_true_sim)\n",
    "\n",
    "m_train_orig = compute_metrics(Y_train_true_orig, Y_train_orig, n_params)\n",
    "m_val_orig   = compute_metrics(Y_val_true_orig,   Y_val_orig,   n_params)\n",
    "m_sim_orig   = compute_metrics(Y_sim_true_orig,   Y_sim_orig,   n_params)\n",
    "\n",
    "print('=== Metrics in ORIGINAL space (%) ===')\n",
    "print(f\"{'Metric':<8} | {'DS1 Train':>12} | {'DS2 Val (1-step)':>16} | {'DS2 Val (sim)':>14}\")\n",
    "print('-' * 60)\n",
    "for k in ['RMSE','MAE','FIT','R2']:\n",
    "    print(f'{k:<8} | {m_train_orig[k]:>12.4f} | {m_val_orig[k]:>16.4f} | {m_sim_orig[k]:>14.4f}')\n",
    "print()\n",
    "print(f'σ (train residuals original): {np.sqrt(m_train_orig[\"RMSE\"]**2):.4f} %  [true ≈ 0.25 %]')\n",
    "\n",
    "model_config = {\n",
    "    'model': 'ARX',\n",
    "    'na': NA, 'nb': NB, 'nk': NK,\n",
    "    'n_params': int(n_params),\n",
    "    'param_names': PARAM_NAMES,\n",
    "    # Lưu theta trong ORIGINAL space (đơn vị %)\n",
    "    'theta_hat': theta_orig.tolist(),\n",
    "    # Lưu sigma2 trong original space (đơn vị %²)\n",
    "    'sigma2': float(sigma2_orig),\n",
    "    # Cũng lưu normalized version để dùng trong prediction (cần normalize input trước)\n",
    "    'theta_hat_normalized': theta_hat.tolist(),\n",
    "    'scaler_min': scaler_min.to_dict(),\n",
    "    'scaler_max': scaler_max.to_dict(),\n",
    "    # Metrics trong original space\n",
    "    'metrics_train': m_train_orig,\n",
    "    'metrics_val':   m_val_orig,\n",
    "    'metrics_sim':   m_sim_orig,\n",
    "    'input_cols': INPUT_COLS,\n",
    "    'output_col': OUTPUT_COL,\n",
    "}\n",
    "\n",
    "with open('arx_model.json', 'w') as f:\n",
    "    json.dump(model_config, f, indent=2)\n",
    "\n",
    "print('\\n✅ Model saved to arx_model.json (theta in ORIGINAL % space)')\n",
    "print(json.dumps({k: model_config[k] for k in ['model','na','nb','nk','n_params','sigma2']}, indent=2))\n"
]))

# ── BUILD NOTEBOOK ────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0"
        }
    },
    "cells": cells
}

out_path = "ARX_Model_Notebook.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f"✅ Notebook written: {out_path}")
print(f"   Total cells: {len(cells)}")
md_count   = sum(1 for c in cells if c['cell_type'] == 'markdown')
code_count = sum(1 for c in cells if c['cell_type'] == 'code')
print(f"   Markdown cells: {md_count}")
print(f"   Code cells    : {code_count}")
