param(
    [string]$InputPath = "ARX_Model_Notebook.ipynb",
    [string]$OutputPath = "ARX_Model_Notebook_VI.ipynb"
)

$ErrorActionPreference = "Stop"

function Replace-Text {
    param(
        [string]$Text,
        [array]$Pairs
    )

    $result = $Text
    foreach ($pair in $Pairs) {
        $result = $result.Replace($pair.old, $pair.new)
    }
    return $result
}

$pairs = @(
    @{ old = "# Experiment: ARX Greenhouse Identification Study"; new = "# Nghiên cứu nhận dạng ARX cho nhà kính mini" },
    @{ old = "Objective:"; new = "Mục tiêu:" },
    @{ old = "- Evaluate the ARX greenhouse baseline with the structure and evidence density expected in a research-style report."; new = "- Đánh giá baseline ARX của nhà kính với cấu trúc và mức độ bằng chứng phù hợp cho một báo cáo kiểu nghiên cứu." },
    @{ old = "- Emphasize full-year data coverage, parameter recovery, long-horizon prediction, residual diagnostics, and model-structure tradeoffs."; new = "- Nhấn mạnh phạm vi dữ liệu 1 năm, khả năng thu hồi tham số, dự đoán dài hạn, chẩn đoán phần dư và trade-off giữa các cấu trúc mô hình." },
    @{ old = "## Study Questions"; new = "## Câu hỏi nghiên cứu" },
    @{ old = "- Does the baseline ARX(2,2,1) recover the true physical direction of each actuator and disturbance term?"; new = "- Baseline ARX(2,2,1) có thu hồi đúng hướng tác động vật lý thật của từng actuator và từng thành phần nhiễu hay không?" },
    @{ old = "- How far does free-run performance fall relative to one-step prediction, and is that gap explained by process noise?"; new = "- Hiệu năng free-run giảm bao nhiêu so với dự đoán 1 bước, và khoảng cách đó có được giải thích bởi nhiễu quá trình hay không?" },
    @{ old = "- Which diagnostic plots are needed to argue that the model is statistically defensible rather than merely visually plausible?"; new = "- Cần những biểu đồ chẩn đoán nào để có thể lập luận rằng mô hình đáng tin về mặt thống kê, chứ không chỉ đẹp về mặt thị giác?" },
    @{ old = "## Workflow"; new = "## Quy trình" },
    @{ old = "1. Configure the experiment and plotting style."; new = "1. Cấu hình thí nghiệm và kiểu trình bày biểu đồ." },
    @{ old = "2. Run the full pipeline and cache all derived tables."; new = "2. Chạy toàn bộ pipeline và tạo các bảng trung gian." },
    @{ old = "3. Characterize the dataset and operating regime."; new = "3. Mô tả bộ dữ liệu và chế độ vận hành." },
    @{ old = "4. Analyze parameter recovery, prediction quality, residual behavior, and model selection."; new = "4. Phân tích khả năng thu hồi tham số, chất lượng dự đoán, hành vi phần dư và việc lựa chọn mô hình." },
    @{ old = "5. Conclude with strengths, limits, and what the baseline can and cannot support."; new = "5. Kết luận về điểm mạnh, giới hạn và những gì baseline có thể hoặc chưa thể hỗ trợ." },
    @{ old = "## Executive Evaluation"; new = "## Đánh giá tổng quan" },
    @{ old = "## Experimental Setup"; new = "## Thiết lập thí nghiệm" },
    @{ old = "## Dataset Characterization"; new = "## Đặc trưng bộ dữ liệu" },
    @{ old = "## Parameter Identification"; new = "## Nhận dạng tham số" },
    @{ old = "## Scale-Aware Parameter Importance"; new = "## Mức độ quan trọng tham số có xét thang đo" },
    @{ old = "## Predictive Performance"; new = "## Hiệu năng dự đoán" },
    @{ old = "## Residual Diagnostics"; new = "## Chẩn đoán phần dư" },
    @{ old = "## Model Structure Search"; new = "## Tìm kiếm cấu trúc mô hình" },
    @{ old = "## Conclusion And Gaps"; new = "## Kết luận và khoảng trống" },
    @{ old = "This section separates one-step accuracy from long-horizon behavior and compares the baseline against the free-run-optimal order found by the search."; new = "Phần này tách riêng độ chính xác 1 bước với hành vi dài hạn, đồng thời so sánh baseline với cấu trúc tối ưu theo free-run tìm được trong quá trình search." },
    @{ old = "A research-style identification section needs more than a coefficient table. It should show estimated-vs-true comparison, confidence intervals, and stability of the autoregressive part."; new = "Một phần nhận dạng theo phong cách nghiên cứu không chỉ dừng ở bảng hệ số. Nó cần cho thấy so sánh estimate-vs-true, khoảng tin cậy và độ ổn định của phần tự hồi quy." },
    @{ old = "Raw ARX coefficients are reported in the original engineering units, so their magnitudes are not directly comparable across regressors."; new = "Các hệ số ARX gốc được báo cáo theo đơn vị kỹ thuật ban đầu, nên độ lớn của chúng không thể so sánh trực tiếp giữa các regressor." },
    @{ old = "The next three figures answer a fairer question: which terms matter most after accounting for variable scale, operating distribution, and lagged dynamic propagation."; new = "Ba hình tiếp theo trả lời một câu hỏi công bằng hơn: term nào quan trọng nhất sau khi đã tính đến thang đo biến, phân bố vận hành và tác động động học có độ trễ." },
    @{ old = "The notebook should not stop at a pretty one-step score. A defensible identification result must combine:"; new = "Notebook không nên dừng lại ở một điểm số 1 bước đẹp. Một kết quả nhận dạng đáng tin cần kết hợp:" },
    @{ old = "- representative data coverage,"; new = "- dữ liệu có phạm vi đại diện," },
    @{ old = "- parameter signs consistent with the generating physics,"; new = "- dấu tham số phù hợp với vật lý sinh dữ liệu," },
    @{ old = "- residuals that behave like unexplained noise,"; new = "- phần dư có hành vi giống nhiễu chưa giải thích," },
    @{ old = "- and long-horizon performance interpreted relative to the deterministic ceiling."; new = "- và hiệu năng dài hạn được diễn giải tương quan với giới hạn xác định." },
    @{ old = "This section documents the baseline configuration and the operating statistics of each split. In a paper, this is the minimum needed to interpret the downstream metrics."; new = "Phần này ghi lại cấu hình baseline và thống kê vận hành của từng split. Trong một bài báo, đây là mức tối thiểu cần có để diễn giải các metric ở phần sau." },
    @{ old = "The original notebook lacked several paper-level figures: a full-year operating overview, monthly distributions, actuator-duty evolution, and setpoint occupancy. Those are added below."; new = "Notebook ban đầu còn thiếu một số hình mang tính báo cáo nghiên cứu: tổng quan vận hành cả năm, phân bố theo tháng, sự thay đổi duty cycle của actuator và tỷ lệ bám setpoint. Các nội dung đó được bổ sung bên dưới." },
    @{ old = "The earlier notebook only partially covered diagnostics. A research-style report needs residual tables, Q-Q evidence, autocorrelation, Ljung-Box p-values, and correlation against inputs."; new = "Notebook trước đây mới chỉ bao phủ một phần chẩn đoán. Một báo cáo kiểu nghiên cứu cần có bảng phần dư, bằng chứng Q-Q, tự tương quan, p-value Ljung-Box và tương quan giữa phần dư với input." },
    @{ old = "A paper should show the search landscape, not just the winner. This section adds both the Pareto-style scatter and na-nb heatmaps for different delays."; new = "Một báo cáo nên thể hiện cả bề mặt tìm kiếm mô hình, không chỉ đưa ra người thắng cuộc. Phần này bổ sung cả đồ thị kiểu Pareto và heatmap na-nb cho các giá trị trễ khác nhau." },
    @{ old = "- The notebook now includes the figures that were missing for a paper-like presentation: full-year operating overview, monthly distributions, actuator-duty evolution, setpoint occupancy, parameter recovery with confidence intervals, stability plot, calibration scatter, rolling error, residual diagnostics, Ljung-Box p-values, and model-search heatmaps."; new = "- Notebook hiện đã bổ sung các hình còn thiếu cho một bài trình bày kiểu paper: tổng quan vận hành cả năm, phân bố theo tháng, biến thiên duty cycle actuator, mức bám setpoint, thu hồi tham số kèm khoảng tin cậy, biểu đồ ổn định, calibration scatter, rolling error, residual diagnostics, p-value Ljung-Box và heatmap search mô hình." },
    @{ old = "- The baseline ARX(2,2,1) is strong as an interpretable identification model because it recovers all parameter signs and passes residual whiteness checks."; new = "- Baseline ARX(2,2,1) mạnh với tư cách một mô hình nhận dạng có thể giải thích được, vì nó thu hồi đúng dấu tất cả tham số và vượt qua kiểm tra residual whiteness." },
    @{ old = "- The large gap between one-step and free-run metrics remains, but it is now shown alongside the theoretical deterministic ceiling, which makes the result interpretable rather than suspicious."; new = "- Khoảng cách lớn giữa 1-step và free-run vẫn tồn tại, nhưng hiện đã được đặt cạnh giới hạn xác định lý thuyết, nên kết quả trở nên dễ diễn giải hơn thay vì đáng nghi." },
    @{ old = "- The order search shows that a different structure can improve free-run validation metrics slightly, but that does not automatically make it the best model for structure recovery or controller design."; new = "- Quá trình search bậc mô hình cho thấy một cấu trúc khác có thể cải thiện metric free-run trên validation, nhưng điều đó không tự động biến nó thành mô hình tốt nhất cho việc thu hồi cấu trúc hoặc thiết kế điều khiển." },
    @{ old = "Performance interpretation"; new = "Diễn giải hiệu năng" },
    @{ old = "Trace interpretation"; new = "Diễn giải đồ thị bám tín hiệu" },
    @{ old = "Calibration interpretation"; new = "Diễn giải hiệu chỉnh" },
    @{ old = "Monthly generalization interpretation"; new = "Diễn giải khả năng tổng quát hóa theo tháng" },
    @{ old = "Seasonality interpretation"; new = "Diễn giải tính mùa vụ" },
    @{ old = "Actuator and setpoint interpretation"; new = "Diễn giải actuator và setpoint" },
    @{ old = "Parameter interpretation"; new = "Diễn giải tham số" },
    @{ old = "Standardized-coefficient interpretation"; new = "Diễn giải hệ số chuẩn hóa" },
    @{ old = "Contribution interpretation"; new = "Diễn giải mức đóng góp" },
    @{ old = "Impulse-response interpretation"; new = "Diễn giải đáp ứng xung" },
    @{ old = "Residual summary interpretation"; new = "Diễn giải tổng quan phần dư" },
    @{ old = "Residual-panel interpretation"; new = "Diễn giải cụm biểu đồ phần dư" },
    @{ old = "Ljung-Box interpretation"; new = "Diễn giải Ljung-Box" },
    @{ old = "Search-table interpretation"; new = "Diễn giải bảng search" },
    @{ old = "Search-frontier interpretation"; new = "Diễn giải biên Pareto" },
    @{ old = "Heatmap interpretation"; new = "Diễn giải heatmap" },
    @{ old = "Dataset interpretation"; new = "Diễn giải bộ dữ liệu" },
    @{ old = "Validation one-step prediction"; new = "Validation dự đoán 1 bước" },
    @{ old = "Test one-step prediction"; new = "Test dự đoán 1 bước" },
    @{ old = "Validation long-horizon behavior"; new = "Validation hành vi dài hạn" },
    @{ old = "Test long-horizon behavior"; new = "Test hành vi dài hạn" },
    @{ old = "Validation calibration scatter"; new = "Validation scatter hiệu chỉnh" },
    @{ old = "Test calibration scatter"; new = "Test scatter hiệu chỉnh" },
    @{ old = "Validation free-run rolling RMSE (1 day window)"; new = "Validation RMSE cửa sổ trượt free-run (cửa sổ 1 ngày)" },
    @{ old = "Test free-run rolling RMSE (1 day window)"; new = "Test RMSE cửa sổ trượt free-run (cửa sổ 1 ngày)" },
    @{ old = "Validation monthly free-run metrics"; new = "Validation metric free-run theo tháng" },
    @{ old = "Test monthly free-run metrics"; new = "Test metric free-run theo tháng" },
    @{ old = "Monthly distribution of Soil_Moisture"; new = "Phân bố theo tháng của Soil_Moisture" },
    @{ old = "Monthly distribution of Temperature"; new = "Phân bố theo tháng của Temperature" },
    @{ old = "Monthly distribution of Humidity"; new = "Phân bố theo tháng của Humidity" },
    @{ old = "Monthly distribution of Light"; new = "Phân bố theo tháng của Light" },
    @{ old = "Monthly actuator duty cycle"; new = "Tỷ lệ bật actuator theo tháng" },
    @{ old = "Monthly switching count"; new = "Số lần chuyển trạng thái theo tháng" },
    @{ old = "Monthly setpoint occupancy"; new = "Tỷ lệ bám setpoint theo tháng" },
    @{ old = "Parameter recovery with 95% CI"; new = "Thu hồi tham số với khoảng tin cậy 95%" },
    @{ old = "AR roots in the complex plane"; new = "Các nghiệm AR trên mặt phẳng phức" },
    @{ old = "Standardized coefficient magnitude on the training split"; new = "Độ lớn hệ số chuẩn hóa trên tập train" },
    @{ old = "Average absolute regressor contribution on the training split"; new = "Đóng góp tuyệt đối trung bình của từng regressor trên tập train" },
    @{ old = "Impulse response to one-standard-deviation input pulses"; new = "Đáp ứng xung với xung input bằng 1 độ lệch chuẩn" },
    @{ old = "Cumulative effect of the same pulses"; new = "Tác động tích lũy của cùng những xung đó" },
    @{ old = "Full-year Soil_Moisture overview"; new = "Tổng quan Soil_Moisture cả năm" },
    @{ old = "Full-year Temperature overview"; new = "Tổng quan Temperature cả năm" },
    @{ old = "Full-year Humidity overview"; new = "Tổng quan Humidity cả năm" },
    @{ old = "Full-year Light overview"; new = "Tổng quan Light cả năm" },
    @{ old = "Actuator activity overview"; new = "Tổng quan hoạt động actuator" },
    @{ old = "Validation residuals over time"; new = "Phần dư Validation theo thời gian" },
    @{ old = "Residual histogram"; new = "Histogram phần dư" },
    @{ old = "Q-Q plot"; new = "Đồ thị Q-Q" },
    @{ old = "Residual autocorrelation"; new = "Tự tương quan phần dư" },
    @{ old = "Residual vs fitted"; new = "Phần dư theo giá trị fitted" },
    @{ old = "Residual-input correlation"; new = "Tương quan giữa phần dư và input" },
    @{ old = "Validation Ljung-Box p-values"; new = "P-value Ljung-Box trên Validation" },
    @{ old = "Test Ljung-Box p-values"; new = "P-value Ljung-Box trên Test" },
    @{ old = "Free-run Pareto frontier"; new = "Biên Pareto cho free-run" },
    @{ old = "Top-10 structures by free-run RMSE"; new = "Top 10 cấu trúc theo RMSE free-run" },
    @{ old = "RMSE_sim heatmap for nk=1"; new = "Heatmap RMSE_sim cho nk=1" },
    @{ old = "RMSE_sim heatmap for nk=2"; new = "Heatmap RMSE_sim cho nk=2" },
    @{ old = "Sample index"; new = "Chỉ số mẫu" },
    @{ old = "Soil Moisture (%)"; new = "Độ ẩm đất (%)" },
    @{ old = "1-step"; new = "1 bước" },
    @{ old = "12-step"; new = "12 bước" },
    @{ old = "Actual "; new = "Thực tế " },
    @{ old = "Predicted "; new = "Dự đoán " },
    @{ old = "Actual"; new = "Thực tế" },
    @{ old = "Predicted"; new = "Dự đoán" },
    @{ old = "ON percentage"; new = "Tỷ lệ ON" },
    @{ old = "Switch count"; new = "Số lần chuyển" },
    @{ old = "Percentage of time"; new = "Phần trăm thời gian" },
    @{ old = "Below low SP"; new = "Dưới low SP" },
    @{ old = "Inside band"; new = "Trong dải" },
    @{ old = "Above high SP"; new = "Trên high SP" },
    @{ old = "Coefficient value"; new = "Giá trị hệ số" },
    @{ old = "Real part"; new = "Phần thực" },
    @{ old = "Imaginary part"; new = "Phần ảo" },
    @{ old = "Standardized beta = theta_i * std(x_i) / std(y)"; new = "Beta chuẩn hóa = theta_i * std(x_i) / std(y)" },
    @{ old = "Mean |x_i * theta_i|"; new = "Giá trị trung bình |x_i * theta_i|" },
    @{ old = "Step ahead"; new = "Bước dự báo" },
    @{ old = "Instantaneous output response"; new = "Đáp ứng đầu ra tức thời" },
    @{ old = "Cumulative response"; new = "Đáp ứng tích lũy" },
    @{ old = "Evidence"; new = "Bằng chứng" },
    @{ old = "Finding"; new = "Phát hiện" },
    @{ old = "Source"; new = "Nguồn" },
    @{ old = "Days"; new = "Số ngày" },
    @{ old = "Sampling seconds"; new = "Số giây lấy mẫu" },
    @{ old = "Train ratio"; new = "Tỉ lệ train" },
    @{ old = "Validation ratio"; new = "Tỉ lệ validation" },
    @{ old = "Test ratio"; new = "Tỉ lệ test" },
    @{ old = "Setting"; new = "Cấu hình" },
    @{ old = "Value"; new = "Giá trị" },
    @{ old = "Block"; new = "Khối" },
    @{ old = "Best free-run model"; new = "Mô hình free-run tốt nhất" },
    @{ old = "Baseline ARX"; new = "Baseline ARX" },
    @{ old = "Best free-run ARX"; new = "ARX free-run tốt nhất" },
    @{ old = "Validation one-step FIT"; new = "Validation FIT 1 bước" },
    @{ old = "Validation free-run FIT"; new = "Validation FIT free-run" },
    @{ old = "Validation deterministic ceiling"; new = "Validation trần xác định" },
    @{ old = "Residual whiteness on validation"; new = "Residual whiteness trên validation" },
    @{ old = "Parameter sign recovery"; new = "Thu hồi dấu tham số" },
    @{ old = "The one-step traces remain close to the measured trajectory because each prediction is corrected by the latest observed output."; new = "Các đường 1 bước vẫn bám sát quỹ đạo đo được vì mỗi dự đoán đều được hiệu chỉnh bởi giá trị output quan sát mới nhất." },
    @{ old = "The 12-step and free-run traces reveal the harder identification problem: once the model must propagate its own state, small coefficient errors accumulate into visible drift."; new = "Các đường 12 bước và free-run cho thấy bài toán nhận dạng khó hơn: khi mô hình phải tự lan truyền trạng thái của chính nó, sai số nhỏ của hệ số sẽ tích lũy thành độ lệch nhìn thấy được." },
    @{ old = "The 12 bước and free-run traces reveal the harder identification problem: once the model must propagate its own state, small coefficient errors accumulate into visible drift."; new = "Các đường 12 bước và free-run cho thấy bài toán nhận dạng khó hơn: khi mô hình phải tự lan truyền trạng thái của chính nó, sai số nhỏ của hệ số sẽ tích lũy thành độ lệch nhìn thấy được." },
    @{ old = "This gap is expected in ARX greenhouse identification and only becomes suspicious if free-run behavior collapses far below the deterministic ceiling, which is not observed here."; new = "Khoảng cách này là điều có thể chờ đợi trong bài toán nhận dạng ARX cho nhà kính và chỉ đáng nghi khi hành vi free-run sụp xuống quá xa dưới trần xác định lý thuyết, điều không xảy ra ở đây." },
    @{ old = "A perfect simulator would place every scatter point on the diagonal; the observed spread is moderate rather than pathological, which is consistent with the reported free-run FIT values."; new = "Một bộ mô phỏng hoàn hảo sẽ đặt mọi điểm scatter nằm trên đường chéo; độ phân tán quan sát được ở đây ở mức vừa phải chứ không bất thường, phù hợp với các giá trị free-run FIT đã báo cáo." },
    @{ old = "Validation rolling RMSE has a median of "; new = "Validation rolling RMSE có median là " },
    @{ old = "while test rolling RMSE has a median of "; new = "trong khi test rolling RMSE có median là " },
    @{ old = "the error does not show a sustained blow-up in a single season."; new = "sai số không cho thấy hiện tượng bùng lên kéo dài ở một mùa riêng lẻ." },
    @{ old = "Validation free-run FIT ranges from "; new = "Validation free-run FIT dao động từ " },
    @{ old = "across months, with the best month at M"; new = "qua các tháng, với tháng tốt nhất là M" },
    @{ old = "and the weakest at M"; new = "và tháng yếu nhất là M" },
    @{ old = "Test free-run FIT ranges from "; new = "Test free-run FIT dao động từ " },
    @{ old = "peaking at M"; new = "đạt đỉnh ở M" },
    @{ old = "and bottoming at M"; new = "và thấp nhất ở M" },
    @{ old = "Validation residual mean/std are "; new = "Validation residual mean/std là " },
    @{ old = "test residual mean/std are "; new = "test residual mean/std là " },
    @{ old = "Residual-versus-fitted scatter acts as a heteroskedasticity check. The absence of a strong funnel shape supports using this model as a defensible linear benchmark."; new = "Biểu đồ phần dư theo fitted đóng vai trò kiểm tra heteroskedasticity. Việc không xuất hiện dạng cái phễu rõ rệt ủng hộ việc dùng mô hình này như một baseline tuyến tính có thể bảo vệ được." },
    @{ old = "The leading rows rank candidate structures by validation free-run performance, so this table is the evidence behind any claim that another order outperforms the baseline."; new = "Các dòng đứng đầu xếp hạng các cấu trúc ứng viên theo hiệu năng free-run trên validation, nên đây là bằng chứng đứng sau mọi nhận định rằng một bậc khác vượt baseline." },
    @{ old = "The Pareto view shows whether better free-run accuracy requires materially more parameters or whether the gain is available at similar complexity."; new = "Góc nhìn Pareto cho thấy liệu độ chính xác free-run tốt hơn có đòi hỏi nhiều tham số hơn đáng kể hay lợi ích đó vẫn đạt được ở mức độ phức tạp tương đương." },
    @{ old = "This is the right evidence for keeping ARX(2,2,1) as the explanatory baseline while still admitting that another structure is slightly better on pure free-run validation."; new = "Đây là loại bằng chứng phù hợp để vẫn giữ ARX(2,2,1) làm baseline có tính giải thích, đồng thời thừa nhận rằng một cấu trúc khác có thể nhỉnh hơn một chút nếu chỉ xét free-run validation thuần túy." },
    @{ old = "Here the best free-run candidate is ARX("; new = "Ở đây ứng viên free-run tốt nhất là ARX(" },
    @{ old = "but the baseline remains competitive enough to defend when interpretability and consistency with the known generator structure are prioritized."; new = "nhưng baseline vẫn đủ cạnh tranh để bảo vệ khi ưu tiên tính giải thích và sự nhất quán với cấu trúc generator đã biết." },
    @{ old = "Validation one-step FIT is "; new = "Validation one-step FIT là " },
    @{ old = "while validation free-run FIT is "; new = "trong khi validation free-run FIT là " },
    @{ old = "so long-horizon recursion costs "; new = "nên phép lặp dài hạn làm mất " },
    @{ old = "percentage points."; new = "điểm phần trăm." },
    @{ old = "Test free-run FIT is "; new = "Test free-run FIT là " },
    @{ old = "and stays within "; new = "và nằm trong khoảng " },
    @{ old = "points of the deterministic ceiling, which suggests that much of the remaining error is consistent with process noise rather than an unmodelled linear trend."; new = "điểm so với trần xác định lý thuyết, điều gợi ý rằng phần lớn sai số còn lại phù hợp với nhiễu quá trình hơn là một xu hướng tuyến tính chưa được mô hình hóa." },
    @{ old = "The search-optimal candidate ARX("; new = "Ứng viên tối ưu theo search ARX(" },
    @{ old = "improves test free-run FIT by "; new = "cải thiện test free-run FIT thêm " },
    @{ old = "points over the baseline, so the notebook now exposes the accuracy-versus-interpretability tradeoff explicitly."; new = "điểm so với baseline, nên notebook hiện thể hiện rõ trade-off giữa độ chính xác và tính giải thích." },
    @{ old = "The dataset spans "; new = "Bộ dữ liệu trải dài " },
    @{ old = " across "; new = " qua " },
    @{ old = ", so the evaluation is no longer confined to a single-month operating regime."; new = ", nên phần đánh giá không còn bị bó hẹp trong một chế độ vận hành của riêng một tháng." },
    @{ old = "The train-regression condition number is "; new = "Condition number của hồi quy trên tập train là " },
    @{ old = "; this is high enough to justify scale-aware importance plots, but not so high that estimation becomes numerically meaningless."; new = "; giá trị này đủ cao để biện minh cho các biểu đồ tầm quan trọng có xét thang đo, nhưng chưa cao đến mức khiến việc ước lượng trở nên vô nghĩa về mặt số học." },
    @{ old = "The greenhouse stays inside the soil-moisture setpoint band for "; new = "Nhà kính duy trì bên trong dải setpoint độ ẩm đất trong khoảng " },
    @{ old = "% of the year on average, with below-band excursions averaging "; new = "% thời gian của cả năm tính theo trung bình, với các thời đoạn nằm dưới dải chiếm trung bình " },
    @{ old = "% of the time."; new = "% thời gian." },
    @{ old = "The model recovers "; new = "Mô hình thu hồi " },
    @{ old = " out of "; new = " trên " },
    @{ old = " coefficient signs correctly, which is the first requirement for a physically interpretable ARX baseline."; new = " dấu hệ số đúng, đây là điều kiện đầu tiên để một baseline ARX có thể giải thích được về mặt vật lý." },
    @{ old = "The 95% intervals cover the true value for "; new = "Các khoảng 95% bao phủ true value cho " },
    @{ old = " parameters, and the largest autoregressive root magnitude is "; new = " tham số, và độ lớn nghiệm tự hồi quy lớn nhất là " },
    @{ old = ", so the fitted dynamics remain stable."; new = ", vì vậy động học đã fit vẫn ổn định." },
    @{ old = "The dominant terms remain "; new = "Các term chi phối vẫn là " },
    @{ old = ", matching the intended persistence-plus-irrigation physics of the generator."; new = ", khớp với logic vật lý đã chủ ý thiết kế trong generator theo hướng quán tính cộng với tưới." },
    @{ old = "The three largest standardized effects are "; new = "Ba hiệu ứng chuẩn hóa lớn nhất là " },
    @{ old = ", which confirms that persistence and irrigation dominate even after scale correction."; new = ", điều này xác nhận rằng quán tính và tưới vẫn là hai yếu tố chi phối ngay cả sau khi hiệu chỉnh thang đo." },
    @{ old = "The dominant contributors are "; new = "Các thành phần đóng góp chi phối là " },
    @{ old = ", which explains why the raw coefficient plot visually concentrates around a1 and the drip terms."; new = ", điều này giải thích vì sao biểu đồ hệ số gốc tập trung chủ yếu quanh a1 và các term của drip." },
    @{ old = "The delayed cumulative shape also explains why b_Drip_2 can exceed b_Drip_1 without being suspicious: the soil process is allowed to absorb irrigation over multiple steps."; new = "Dạng tích lũy có độ trễ cũng giải thích vì sao b_Drip_2 có thể lớn hơn b_Drip_1 mà không đáng nghi: quá trình đất được phép hấp thụ tác động tưới qua nhiều bước." },
    @{ old = "The largest absolute residual-input correlation on validation is "; new = "Tương quan tuyệt đối lớn nhất giữa phần dư và input trên validation là " },
    @{ old = "; values near zero indicate that major input-driven structure has already been captured by the model."; new = "; các giá trị gần 0 cho thấy phần cấu trúc chính do input điều khiển đã được mô hình nắm bắt." },
    @{ old = "The Q-Q plot and histogram are rough shape diagnostics; mild departures from Gaussianity are acceptable once the main serial correlation has been removed."; new = "Đồ thị Q-Q và histogram là các công cụ chẩn đoán hình dạng phân bố ở mức gần đúng; sai lệch nhẹ khỏi Gaussian vẫn chấp nhận được khi tương quan chuỗi chính đã được loại bỏ." },
    @{ old = "The Đồ thị Q-Q and histogram are rough shape diagnostics; mild departures from Gaussianity are acceptable once the main serial correlation has been removed."; new = "Đồ thị Q-Q và histogram là các công cụ chẩn đoán hình dạng phân bố ở mức gần đúng; sai lệch nhẹ khỏi Gaussian vẫn chấp nhận được khi tương quan chuỗi chính đã được loại bỏ." },
    @{ old = "The minimum validation Ljung-Box p-value over the first 20 lags is "; new = "P-value Ljung-Box nhỏ nhất của validation trong 20 lag đầu là " },
    @{ old = "; the test minimum is "; new = "; giá trị nhỏ nhất trên test là " },
    @{ old = "The top-ranked candidate is ARX("; new = "Ứng viên xếp hạng cao nhất là ARX(" },
    @{ old = ") with validation FIT_sim="; new = ") với validation FIT_sim=" },
    @{ old = " and RMSE_sim="; new = " và RMSE_sim=" },
    @{ old = "The heatmaps reveal whether the optimum is isolated or belongs to a broader low-error region in the na-nb grid."; new = "Các heatmap cho thấy điểm tối ưu là đơn lẻ hay thuộc về một vùng sai số thấp rộng hơn trong lưới na-nb." }
)

$inputFullPath = Join-Path (Get-Location) $InputPath
$outputFullPath = Join-Path (Get-Location) $OutputPath

$raw = Get-Content $inputFullPath -Raw -Encoding UTF8
$notebook = $raw | ConvertFrom-Json

foreach ($cell in $notebook.cells) {
    $translatedSource = @()
    foreach ($line in $cell.source) {
        $translatedSource += (Replace-Text -Text $line -Pairs $pairs)
    }
    $cell.source = $translatedSource

    if ($cell.cell_type -eq "code") {
        $cell.execution_count = $null
        $cell.outputs = @()
        $cell.metadata = @{}
    }
}

$json = $notebook | ConvertTo-Json -Depth 100
[System.IO.File]::WriteAllText($outputFullPath, $json, [System.Text.UTF8Encoding]::new($true))

Write-Output "Đã tạo notebook tiếng Việt có dấu tại: $outputFullPath"
